[FIREBASE_CREDENTIALS]
type = "service_account"
project_id = "daily-huddle-8e906"
private_key_id = "76a9c3e0379947a19eda8a657ea27479bebe72df"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFA..."
client_email = "firebase-adminsdk-fbsvc@daily-huddle-8e906.iam.gserviceaccount.com"
client_id = "105846961328615504447"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40daily-huddle-8e906.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
